"use strict";
exports.__esModule = true;
var message = 'Welcome';
console.log(message);
var x = 10;
var y = 20;
var sum;
var title = 'IAmNotGay';
sum = x + y;
var isBeginner = true;
var total = 0;
var name = 'Ernest';
var sentence = "My name is ".concat(name);
console.log(sentence);
var n = null;
var u = undefined;
var arr1 = [1, 2, 3];
var arr2 = [4, 5, 6];
var strArr = ['1', '2', '3'];
var strArr2 = ['4', '5', '6'];
console.log(strArr);
console.log(strArr2);
var mixedArr = ['Ernest', 2];
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
;
var c = Color.Green;
console.log(c);
